# Why?
# https://www.jvt.me/posts/2024/04/12/use-renovate/

name: Renovate

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log levels based on severity. DEBUG, INFO, WARN, ERROR, FATAL
        required: false
        default: 'info'
        type: string
  push:
    branches:
      - main

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.12
        with:
          configurationFile: .github/renovate.json5
          # https://docs.renovatebot.com/modules/platform/github/#running-using-a-fine-grained-token
          token: ${{ steps.app-token.outputs.token }}
        env:
            LOG_LEVEL: ${{ github.event.inputs.logLevel || 'info' }}
            RENOVATE_REPOSITORIES: ${{ github.repository }}
